require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contract_types", type: :request do
  
  # ContractType. As you add validations to ContractType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ContractType.create! valid_attributes
      get contract_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contract_type = ContractType.create! valid_attributes
      get contract_type_url(contract_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contract_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      contract_type = ContractType.create! valid_attributes
      get edit_contract_type_url(contract_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ContractType" do
        expect {
          post contract_types_url, params: { contract_type: valid_attributes }
        }.to change(ContractType, :count).by(1)
      end

      it "redirects to the created contract_type" do
        post contract_types_url, params: { contract_type: valid_attributes }
        expect(response).to redirect_to(contract_type_url(ContractType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ContractType" do
        expect {
          post contract_types_url, params: { contract_type: invalid_attributes }
        }.to change(ContractType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contract_types_url, params: { contract_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contract_type" do
        contract_type = ContractType.create! valid_attributes
        patch contract_type_url(contract_type), params: { contract_type: new_attributes }
        contract_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contract_type" do
        contract_type = ContractType.create! valid_attributes
        patch contract_type_url(contract_type), params: { contract_type: new_attributes }
        contract_type.reload
        expect(response).to redirect_to(contract_type_url(contract_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        contract_type = ContractType.create! valid_attributes
        patch contract_type_url(contract_type), params: { contract_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contract_type" do
      contract_type = ContractType.create! valid_attributes
      expect {
        delete contract_type_url(contract_type)
      }.to change(ContractType, :count).by(-1)
    end

    it "redirects to the contract_types list" do
      contract_type = ContractType.create! valid_attributes
      delete contract_type_url(contract_type)
      expect(response).to redirect_to(contract_types_url)
    end
  end
end
