require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dentist_aggregations", type: :request do
  
  # DentistAggregation. As you add validations to DentistAggregation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DentistAggregation.create! valid_attributes
      get dentist_aggregations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dentist_aggregation = DentistAggregation.create! valid_attributes
      get dentist_aggregation_url(dentist_aggregation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dentist_aggregation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dentist_aggregation = DentistAggregation.create! valid_attributes
      get edit_dentist_aggregation_url(dentist_aggregation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DentistAggregation" do
        expect {
          post dentist_aggregations_url, params: { dentist_aggregation: valid_attributes }
        }.to change(DentistAggregation, :count).by(1)
      end

      it "redirects to the created dentist_aggregation" do
        post dentist_aggregations_url, params: { dentist_aggregation: valid_attributes }
        expect(response).to redirect_to(dentist_aggregation_url(DentistAggregation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DentistAggregation" do
        expect {
          post dentist_aggregations_url, params: { dentist_aggregation: invalid_attributes }
        }.to change(DentistAggregation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dentist_aggregations_url, params: { dentist_aggregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dentist_aggregation" do
        dentist_aggregation = DentistAggregation.create! valid_attributes
        patch dentist_aggregation_url(dentist_aggregation), params: { dentist_aggregation: new_attributes }
        dentist_aggregation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dentist_aggregation" do
        dentist_aggregation = DentistAggregation.create! valid_attributes
        patch dentist_aggregation_url(dentist_aggregation), params: { dentist_aggregation: new_attributes }
        dentist_aggregation.reload
        expect(response).to redirect_to(dentist_aggregation_url(dentist_aggregation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dentist_aggregation = DentistAggregation.create! valid_attributes
        patch dentist_aggregation_url(dentist_aggregation), params: { dentist_aggregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dentist_aggregation" do
      dentist_aggregation = DentistAggregation.create! valid_attributes
      expect {
        delete dentist_aggregation_url(dentist_aggregation)
      }.to change(DentistAggregation, :count).by(-1)
    end

    it "redirects to the dentist_aggregations list" do
      dentist_aggregation = DentistAggregation.create! valid_attributes
      delete dentist_aggregation_url(dentist_aggregation)
      expect(response).to redirect_to(dentist_aggregations_url)
    end
  end
end
