require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dh_aggregations", type: :request do
  
  # DhAggregation. As you add validations to DhAggregation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DhAggregation.create! valid_attributes
      get dh_aggregations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dh_aggregation = DhAggregation.create! valid_attributes
      get dh_aggregation_url(dh_aggregation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dh_aggregation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dh_aggregation = DhAggregation.create! valid_attributes
      get edit_dh_aggregation_url(dh_aggregation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DhAggregation" do
        expect {
          post dh_aggregations_url, params: { dh_aggregation: valid_attributes }
        }.to change(DhAggregation, :count).by(1)
      end

      it "redirects to the created dh_aggregation" do
        post dh_aggregations_url, params: { dh_aggregation: valid_attributes }
        expect(response).to redirect_to(dh_aggregation_url(DhAggregation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DhAggregation" do
        expect {
          post dh_aggregations_url, params: { dh_aggregation: invalid_attributes }
        }.to change(DhAggregation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dh_aggregations_url, params: { dh_aggregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dh_aggregation" do
        dh_aggregation = DhAggregation.create! valid_attributes
        patch dh_aggregation_url(dh_aggregation), params: { dh_aggregation: new_attributes }
        dh_aggregation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dh_aggregation" do
        dh_aggregation = DhAggregation.create! valid_attributes
        patch dh_aggregation_url(dh_aggregation), params: { dh_aggregation: new_attributes }
        dh_aggregation.reload
        expect(response).to redirect_to(dh_aggregation_url(dh_aggregation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dh_aggregation = DhAggregation.create! valid_attributes
        patch dh_aggregation_url(dh_aggregation), params: { dh_aggregation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dh_aggregation" do
      dh_aggregation = DhAggregation.create! valid_attributes
      expect {
        delete dh_aggregation_url(dh_aggregation)
      }.to change(DhAggregation, :count).by(-1)
    end

    it "redirects to the dh_aggregations list" do
      dh_aggregation = DhAggregation.create! valid_attributes
      delete dh_aggregation_url(dh_aggregation)
      expect(response).to redirect_to(dh_aggregations_url)
    end
  end
end
