require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prosthodontic_masters", type: :request do
  
  # ProsthodonticMaster. As you add validations to ProsthodonticMaster, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProsthodonticMaster.create! valid_attributes
      get prosthodontic_masters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prosthodontic_master = ProsthodonticMaster.create! valid_attributes
      get prosthodontic_master_url(prosthodontic_master)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prosthodontic_master_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      prosthodontic_master = ProsthodonticMaster.create! valid_attributes
      get edit_prosthodontic_master_url(prosthodontic_master)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProsthodonticMaster" do
        expect {
          post prosthodontic_masters_url, params: { prosthodontic_master: valid_attributes }
        }.to change(ProsthodonticMaster, :count).by(1)
      end

      it "redirects to the created prosthodontic_master" do
        post prosthodontic_masters_url, params: { prosthodontic_master: valid_attributes }
        expect(response).to redirect_to(prosthodontic_master_url(ProsthodonticMaster.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProsthodonticMaster" do
        expect {
          post prosthodontic_masters_url, params: { prosthodontic_master: invalid_attributes }
        }.to change(ProsthodonticMaster, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prosthodontic_masters_url, params: { prosthodontic_master: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prosthodontic_master" do
        prosthodontic_master = ProsthodonticMaster.create! valid_attributes
        patch prosthodontic_master_url(prosthodontic_master), params: { prosthodontic_master: new_attributes }
        prosthodontic_master.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prosthodontic_master" do
        prosthodontic_master = ProsthodonticMaster.create! valid_attributes
        patch prosthodontic_master_url(prosthodontic_master), params: { prosthodontic_master: new_attributes }
        prosthodontic_master.reload
        expect(response).to redirect_to(prosthodontic_master_url(prosthodontic_master))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prosthodontic_master = ProsthodonticMaster.create! valid_attributes
        patch prosthodontic_master_url(prosthodontic_master), params: { prosthodontic_master: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prosthodontic_master" do
      prosthodontic_master = ProsthodonticMaster.create! valid_attributes
      expect {
        delete prosthodontic_master_url(prosthodontic_master)
      }.to change(ProsthodonticMaster, :count).by(-1)
    end

    it "redirects to the prosthodontic_masters list" do
      prosthodontic_master = ProsthodonticMaster.create! valid_attributes
      delete prosthodontic_master_url(prosthodontic_master)
      expect(response).to redirect_to(prosthodontic_masters_url)
    end
  end
end
