require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/staff_infos", type: :request do
  
  # StaffInfo. As you add validations to StaffInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StaffInfo.create! valid_attributes
      get staff_infos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      staff_info = StaffInfo.create! valid_attributes
      get staff_info_url(staff_info)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_staff_info_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      staff_info = StaffInfo.create! valid_attributes
      get edit_staff_info_url(staff_info)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StaffInfo" do
        expect {
          post staff_infos_url, params: { staff_info: valid_attributes }
        }.to change(StaffInfo, :count).by(1)
      end

      it "redirects to the created staff_info" do
        post staff_infos_url, params: { staff_info: valid_attributes }
        expect(response).to redirect_to(staff_info_url(StaffInfo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StaffInfo" do
        expect {
          post staff_infos_url, params: { staff_info: invalid_attributes }
        }.to change(StaffInfo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post staff_infos_url, params: { staff_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested staff_info" do
        staff_info = StaffInfo.create! valid_attributes
        patch staff_info_url(staff_info), params: { staff_info: new_attributes }
        staff_info.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the staff_info" do
        staff_info = StaffInfo.create! valid_attributes
        patch staff_info_url(staff_info), params: { staff_info: new_attributes }
        staff_info.reload
        expect(response).to redirect_to(staff_info_url(staff_info))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        staff_info = StaffInfo.create! valid_attributes
        patch staff_info_url(staff_info), params: { staff_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested staff_info" do
      staff_info = StaffInfo.create! valid_attributes
      expect {
        delete staff_info_url(staff_info)
      }.to change(StaffInfo, :count).by(-1)
    end

    it "redirects to the staff_infos list" do
      staff_info = StaffInfo.create! valid_attributes
      delete staff_info_url(staff_info)
      expect(response).to redirect_to(staff_infos_url)
    end
  end
end
