require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/treatment_coordinators", type: :request do
  
  # TreatmentCoordinator. As you add validations to TreatmentCoordinator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TreatmentCoordinator.create! valid_attributes
      get treatment_coordinators_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      treatment_coordinator = TreatmentCoordinator.create! valid_attributes
      get treatment_coordinator_url(treatment_coordinator)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_treatment_coordinator_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      treatment_coordinator = TreatmentCoordinator.create! valid_attributes
      get edit_treatment_coordinator_url(treatment_coordinator)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TreatmentCoordinator" do
        expect {
          post treatment_coordinators_url, params: { treatment_coordinator: valid_attributes }
        }.to change(TreatmentCoordinator, :count).by(1)
      end

      it "redirects to the created treatment_coordinator" do
        post treatment_coordinators_url, params: { treatment_coordinator: valid_attributes }
        expect(response).to redirect_to(treatment_coordinator_url(TreatmentCoordinator.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TreatmentCoordinator" do
        expect {
          post treatment_coordinators_url, params: { treatment_coordinator: invalid_attributes }
        }.to change(TreatmentCoordinator, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post treatment_coordinators_url, params: { treatment_coordinator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested treatment_coordinator" do
        treatment_coordinator = TreatmentCoordinator.create! valid_attributes
        patch treatment_coordinator_url(treatment_coordinator), params: { treatment_coordinator: new_attributes }
        treatment_coordinator.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the treatment_coordinator" do
        treatment_coordinator = TreatmentCoordinator.create! valid_attributes
        patch treatment_coordinator_url(treatment_coordinator), params: { treatment_coordinator: new_attributes }
        treatment_coordinator.reload
        expect(response).to redirect_to(treatment_coordinator_url(treatment_coordinator))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        treatment_coordinator = TreatmentCoordinator.create! valid_attributes
        patch treatment_coordinator_url(treatment_coordinator), params: { treatment_coordinator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested treatment_coordinator" do
      treatment_coordinator = TreatmentCoordinator.create! valid_attributes
      expect {
        delete treatment_coordinator_url(treatment_coordinator)
      }.to change(TreatmentCoordinator, :count).by(-1)
    end

    it "redirects to the treatment_coordinators list" do
      treatment_coordinator = TreatmentCoordinator.create! valid_attributes
      delete treatment_coordinator_url(treatment_coordinator)
      expect(response).to redirect_to(treatment_coordinators_url)
    end
  end
end
