class ChangeColumnType < ActiveRecord::Migration[7.0]
  def change
    change_column(:dh_aggregations, :no_of_reservations, :integer, default: 0, using: 'no_of_reservations::integer')
    change_column(:dh_aggregations, :people_maintenance, :integer, default: 0, using: 'people_maintenance::integer')
    change_column(:dh_aggregations, :people_treatment, :integer, default: 0, using: 'people_treatment::integer')
    change_column(:dh_aggregations, :people_own_expense, :integer, default: 0, using: 'people_own_expense::integer')
    change_column(:dh_aggregations, :oral_count, :integer, default: 0, using: 'oral_count::integer')
    change_column(:dh_aggregations, :out_of_the_decline, :integer, default: 0, using: 'out_of_the_decline::integer')
    change_column(:dh_aggregations, :cancellation_tel, :integer, default: 0, using: 'cancellation_tel::integer')
    change_column(:dh_aggregations, :cancellation_without, :integer, default: 0, using: 'cancellation_without::integer')
    change_column(:dh_aggregations, :insurance_maintenance, :integer, default: 0, using: 'insurance_maintenance::integer')
    change_column(:dh_aggregations, :insurance_treatment, :integer, default: 0, using: 'insurance_treatment::integer')
    change_column(:dh_aggregations, :own_income, :integer, default: 0, using: 'own_income::integer')
    change_column(:dh_aggregations, :miscc_income, :integer, default: 0, using: 'miscc_income::integer')
    change_column(:dh_aggregations, :no_of_people, :integer, default: 0, using: 'no_of_people::integer')
    change_column(:dh_aggregations, :appt_confm_people, :integer, default: 0, using: 'appt_confm_people::integer')
    change_column(:dh_aggregations, :interval_1m_people, :integer, default: 0, using: 'interval_1m_people::integer')
    change_column(:dh_aggregations, :interval_1m_tel, :integer, default: 0, using: 'interval_1m_tel::integer')
    change_column(:dh_aggregations, :interval_1m_without, :integer, default: 0, using: 'interval_1m_without::integer')
    change_column(:dh_aggregations, :interval_2m_people, :integer, default: 0, using: 'interval_2m_people::integer')
    change_column(:dh_aggregations, :interval_2m_tel, :integer, default: 0, using: 'interval_2m_tel::integer')
    change_column(:dh_aggregations, :interval_2m_without, :integer, default: 0, using: 'interval_2m_without::integer')
    change_column(:dh_aggregations, :interval_3m_people, :integer, default: 0, using: 'interval_3m_people::integer')
    change_column(:dh_aggregations, :interval_3m_tel, :integer, default: 0, using: 'interval_3m_tel::integer')
    change_column(:dh_aggregations, :interval_3m_without, :integer, default: 0, using: 'interval_3m_without::integer')
    change_column(:dh_aggregations, :interval_4m_people, :integer, default: 0, using: 'interval_4m_people::integer')
    change_column(:dh_aggregations, :interval_4m_tel, :integer, default: 0, using: 'interval_4m_tel::integer')
    change_column(:dh_aggregations, :interval_4m_without, :integer, default: 0, using: 'interval_4m_without::integer')
    change_column(:dh_aggregations, :interval_6m_people, :integer, default: 0, using: 'interval_6m_people::integer')
    change_column(:dh_aggregations, :interval_6m_tel, :integer, default: 0, using: 'interval_6m_tel::integer')
    change_column(:dh_aggregations, :interval_6m_without, :integer, default: 0, using: 'interval_6m_without::integer')
    change_column(:dh_aggregations, :spt2, :integer, default: 0, using: 'spt2::integer')
    change_column(:dh_aggregations, :spt1, :integer, default: 0, using: 'spt1::integer')
    change_column(:dh_aggregations, :g_p_heavy_defense, :integer, default: 0, using: 'g_p_heavy_defense::integer')
    change_column(:dh_aggregations, :no_of_referrals, :integer, default: 0, using: 'no_of_referrals::integer')
    change_column(:dh_aggregations, :note, :integer, default: 0, using: 'note::integer')
    change_column(:dh_aggregations, :oral_func, :integer, default: 0, using: 'oral_func::integer')
    change_column(:dh_aggregations, :med_prac_rev, :integer, default: 0, using: 'med_prac_rev::integer')
    change_column(:dh_aggregations, :act_med_exam_days, :integer, default: 0, using: 'act_med_exam_days::integer')
    change_column(:dh_aggregations, :one_day_no_reservation, :integer, default: 0, using: 'one_day_no_reservation::integer')
  end
end
